// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://subnrhydadsdgjtvnlft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1Ym5yaHlkYWRzZGdqdHZubGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyMzQ1MjksImV4cCI6MjA4NTgxMDUyOX0.qwjMdbKl8980eQxU8pxRM6IO-SFJSEXc0UMCWd2THbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);